- allocated_cpu_cores: 0.0
  allocated_disk_gb: 0
  allocated_ports: []
  allocated_ram_mb: 0
  cluster_id: ''
  customer_id: CID-0001
  customer_uuid: 7ea24055-9eb4-4b3a-9219-1db40b9d3fa0
  minecraft_version: ''
  modpack_name: ''
  node_id: ''
  player_limit: 0
  provisioning_status: pending
  region: ''
  server_type: ''
  service_created_timestamp: '2026-05-09T13:45:55'
  service_id: SVC-0001
  service_ip: ''
  service_name: WEB1
  service_provision_source: ''
  service_rcon_port: null
  service_rcon_pwd: ''
  service_sku: ''
  service_status: provisioning
  service_subdomain: ''
  service_terminated_timestamp: null
  service_type: web
  service_updated_timestamp: '2026-05-09T13:45:55'
  uuid: 98c80f0d-3f0e-4667-a233-f648fa8b57d1
